import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useLocale, NextIntlClientProvider, useMessages } from "next-intl";
import { notFound } from "next/navigation";
import LanguageDetection from "@/components/core/LanguageDetection";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Selem App",
  description: "Generated by Shady Hussein",
};

const locales = ["en", "ar"];

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = useMessages();
  const localization = useLocale();

  const isValidLocale = locales.some((cur) => cur === locale);
  if (!isValidLocale) notFound();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider locale={localization} messages={messages}>
          <div>
            <div className="w-24 ml-auto my-4 mx-6">
              <LanguageDetection />
            </div>
            {children}
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
